spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/12bit
    username: admin
    password: testPassword@
    hikari:
      maximum-pool-size: 24
      minimum-idle: 5
  data:
    redis:
      port: 6379
      host: "localhost"
      ssl:
        enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      realworld: DEBUG
    org:
      springframework: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace
swagger-servers: #해당 설정이 빠져있다면 기본적으로 http://localhost:8080 으로 설정됩니다.
  urls:
    - http://localhost:8080
    - https://api-test.realworld.to